#include <math.h>
#include <stdio.h>
#include "identification_iq.h"

static int within_relative(float actual, float reference, float limit)
{
    float denominator = fmaxf(fabsf(reference), 1.0e-6F);
    return fabsf(actual - reference) / denominator <= limit;
}

int main(void)
{
    IdentificationIqConfig_t config;
    IdentificationIqState_t state;
    IdentificationIqInput_t input = {0};
    IdentificationIqOutput_t output = {0};
    IdentificationIq_DefaultConfig(&config);
    config.sample_capacity = 128U;
    config.repeat_times = 2U;
    config.max_steps = 6U;
    config.wait_edges = 1U;
    config.injection_half_period_cycles = 80U;
    config.rs_hold_cycles = 100U;
    config.current_start_pu = MC_CONST(0.03);
    config.current_final_pu = MC_CONST(0.18);
    config.current_step_pu = MC_CONST(0.03);
    config.current_limit_pu = MC_CONST(0.8);
    config.rs_current_target_pu = MC_CONST(0.15);
    config.rs_threshold_pu = MC_CONST(0.01);
    config.rs_voltage_step_pu = MC_CONST(0.02);
    config.injection_voltage_pu = MC_CONST(0.10);
    /* Match the firmware's 5 kHz / 800 V / 1 Wb flux integration scale. */
    config.voltage_to_flux_step = MC_CONST(0.16);
    IdentificationIq_Init(&state, &config);
    IdentificationIq_Start(&state);

    const float plant_resistance = 0.2F;
    const float plant_ad0 = 0.1F;
    const float plant_add = 20.0F;
    const float plant_aq0 = 0.2F;
    const float plant_aqq = 0.5F;
    const float plant_adq = 0.2F;
    float plant_flux_d = 0.0F;
    float plant_flux_q = 0.0F;
    float current_d = 0.0F;
    float current_q = 0.0F;
    unsigned iteration;
    for (iteration = 0U; iteration < 1000000U; ++iteration)
    {
        input.current_d_pu = McMath_FromFloat(current_d);
        input.current_q_pu = McMath_FromFloat(current_q);
        IdentificationIq_Run(&state, &input, &output);
        float voltage_d = McMath_ToFloat(output.voltage_d_pu);
        float voltage_q = McMath_ToFloat(output.voltage_q_pu);
        plant_flux_d += 0.16F * (voltage_d
                      - plant_resistance * current_d);
        plant_flux_q += 0.16F * (voltage_q
                      - plant_resistance * current_q);
        float absolute_flux_d = fabsf(plant_flux_d);
        float absolute_flux_q = fabsf(plant_flux_q);
        float d_term = plant_ad0
                     + plant_add * powf(absolute_flux_d, 5.0F)
                     + 0.5F * plant_adq * absolute_flux_d
                     * absolute_flux_q * absolute_flux_q;
        float q_term = plant_aq0 + plant_aqq * absolute_flux_q
                     + (plant_adq / 3.0F)
                     * absolute_flux_d * absolute_flux_d * absolute_flux_d;
        current_d = d_term * plant_flux_d;
        current_q = q_term * plant_flux_q;
        if (state.state == IDENTIFICATION_IQ_DONE
            || state.state == IDENTIFICATION_IQ_FAILED)
            break;
    }
    if (state.state != IDENTIFICATION_IQ_DONE || !state.coefficients.valid)
    {
        fprintf(stderr,
                "FAIL identification: iteration=%u state=%u error=%u steps=%u samples=%u\n",
                iteration, (unsigned)state.state, (unsigned)state.error,
                state.step_index, state.sample_count);
        for (unsigned index = 0U; index < state.step_index; ++index)
        {
            fprintf(stderr,
                    "  step=%u d=(%.8f, %.8f, %u) q=(%.8f, %.8f, %u)\n",
                    index,
                    McMath_ToFloat(state.d_results[index].current_pu),
                    McMath_ToFloat(state.d_results[index].maximum_flux_pu),
                    state.d_results[index].valid ? 1U : 0U,
                    McMath_ToFloat(state.q_results[index].current_pu),
                    McMath_ToFloat(state.q_results[index].maximum_flux_pu),
                    state.q_results[index].valid ? 1U : 0U);
        }
        return 1;
    }
    float result_ad0 = McMath_ToFloat(state.coefficients.ad0);
    float result_add = McMath_ToFloat(state.coefficients.add);
    float result_aq0 = McMath_ToFloat(state.coefficients.aq0);
    float result_aqq = McMath_ToFloat(state.coefficients.aqq);
    float result_adq = McMath_ToFloat(state.coefficients.adq);
    /* Golden values are generated by this deterministic plant with the
     * FLOAT_REF backend.  The same 1% bound is then applied to Q24. */
    if (state.step_index != config.max_steps
        || !isfinite(result_ad0) || !isfinite(result_adq)
        || !within_relative(result_ad0, 0.08390631F, 0.01F)
        || !within_relative(result_add, 17.86937332F, 0.01F)
        || !within_relative(result_aq0, 0.15541813F, 0.01F)
        || !within_relative(result_aqq, 0.56980562F, 0.01F)
        || !within_relative(result_adq, 1.91263592F, 0.01F)
        || McMath_Diagnostics.saturation_count != 0U
        || McMath_Diagnostics.divide_by_zero_count != 0U
        || McMath_Diagnostics.invalid_input_count != 0U)
    {
        fprintf(stderr, "FAIL identification result bounds\n");
        return 1;
    }
    printf("PASS: identification IQ state regression in %u cycles "
           "ad0=%.8f add=%.8f aq0=%.8f aqq=%.8f adq=%.8f\n",
           iteration + 1U,
           result_ad0, result_add, result_aq0, result_aqq, result_adq);
    return 0;
}
